<template>
  <section class="py-14">
    <div class="mx-auto max-w-5xl px-4 prose prose-slate">
      <h1>Approach</h1>
      <p><RouterLink to="/approach/emotional-intelligence" class="font-bold text-brand-700 hover:text-brand-800 no-underline hover:underline">Emotional Intelligence</RouterLink> is the foundation of all my work. The capacity to recognize, understand, and skillfully navigate emotions—our own and others'—shapes every relationship we have. When we develop this core competency, we gain access to clearer thinking, deeper connection, and more effective action. My practice offers a structured path to build these essential skills.</p>
      <p>I draw from four complementary modalities: <RouterLink to="/approach/nvc" class="font-bold text-brand-700 hover:text-brand-800 no-underline hover:underline">Non-Violent Communication (NVC)</RouterLink> centers universal human needs and teaches us to make clear, connecting requests. <RouterLink to="/approach/ifs" class="font-bold text-brand-700 hover:text-brand-800 no-underline hover:underline">Internal Family Systems (IFS-informed)</RouterLink> meets our inner parts with curiosity rather than judgment. <RouterLink to="/approach/mindfulness" class="font-bold text-brand-700 hover:text-brand-800 no-underline hover:underline">Mindfulness</RouterLink> stabilizes attention and supports nervous-system regulation. <RouterLink to="/approach/attitudinal-healing" class="font-bold text-brand-700 hover:text-brand-800 no-underline hover:underline">Attitudinal Healing</RouterLink> helps us shift from fear-based reactions to love-centered choices. Together, these approaches create a practical toolkit for emotional growth.</p>
      <p><RouterLink to="/approach/conflict-resolution" class="font-bold text-brand-700 hover:text-brand-800 no-underline hover:underline">Conflict Resolution</RouterLink> emerges naturally when we commit to mutual understanding. Rather than trying to win arguments or prove who's right, we learn to listen for the needs beneath the positions. When both people feel genuinely heard, defensiveness softens and creative solutions become possible. This shift—from opposition to collaboration—transforms how we navigate disagreement in every area of life.</p>
      <p><RouterLink to="/approach/outcomes" class="font-bold text-brand-700 hover:text-brand-800 no-underline hover:underline">Mutually Satisfying Outcomes</RouterLink> are the destination of this work. When we combine emotional intelligence, skilled communication, and genuine understanding, we create agreements that honor everyone's needs. Sessions are practical, gentle, and skills-focused—we practice reflective listening, feelings and needs translation, and request-making, then integrate actions at a sustainable pace. You leave with tools you can use immediately and a clearer path toward the connections you want.</p>
    </div>
  </section>
</template>